# Generated by Django 5.2.16 on 2026-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=80)),
                ('time_label', models.CharField(max_length=80)),
                ('day_offset', models.SmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='info', max_length=20)),
            ],
            options={
                'ordering': ['day_offset', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('since', models.CharField(max_length=80)),
                ('status', models.CharField(default='info', max_length=20)),
            ],
            options={
                'ordering': ['status', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DashboardHealthMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=40)),
                ('normal_count', models.PositiveSmallIntegerField(default=0)),
                ('abnormal_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['year', 'month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_dashboard_health_month')],
            },
        ),
    ]
