# Generated by Django 5.2.16 on 2026-07-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_short_text', models.TextField(blank=True)),
                ('patient_long_text', models.TextField(blank=True)),
                ('doctor_information', models.TextField(blank=True)),
                ('causes_low', models.TextField(blank=True)),
                ('causes_high', models.TextField(blank=True)),
                ('influencing_factors', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('pruefung', 'Prüfung'), ('freigegeben', 'Freigegeben')], db_index=True, default='entwurf', max_length=20)),
                ('changed_by', models.CharField(default='Admin', max_length=120)),
                ('changed_at_label', models.CharField(blank=True, max_length=40)),
                ('analyte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entry', to='labs.labanalyte')),
            ],
            options={
                'ordering': ['analyte__group__name', 'analyte__display_name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('source_type', models.CharField(choices=[('leitlinie', 'Leitlinie'), ('laborlexikon', 'Laborlexikon'), ('fachliteratur', 'Fachliteratur'), ('intern', 'Intern'), ('demo', 'Demo')], default='demo', max_length=24)),
                ('source_date', models.CharField(blank=True, max_length=80)),
                ('reference', models.CharField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='knowledge.knowledgeentry')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('date_label', models.CharField(max_length=40)),
                ('changed_by', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgeentry')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['status', 'version'], name='knowledge_k_status_00bb7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeversion',
            constraint=models.UniqueConstraint(fields=('entry', 'version'), name='unique_knowledge_entry_version'),
        ),
    ]
