# apps/knowledge/migrations/0002_knowledgeentry_chart_color.py

# Generated by Django 5.2.16 on 2026-07-09

from django.db import migrations, models


FARBEN = [
    '#b91c1c', '#dc2626', '#ea580c', '#d97706', '#ca8a04', '#65a30d', '#16a34a', '#059669',
    '#0d9488', '#0891b2', '#0284c7', '#2563eb', '#4f46e5', '#7c3aed', '#9333ea', '#c026d3',
    '#db2777', '#e11d48', '#be123c', '#9f1239', '#0f766e', '#0369a1', '#1d4ed8', '#4338ca',
    '#6d28d9', '#86198f', '#a21caf', '#be185d', '#92400e', '#166534', '#0f5297', '#475569'
]


FESTE_FARBEN = {
    'leukozyten': '#2563eb',
    'erythrozyten': '#dc2626',
    'haemoglobin': '#b91c1c',
    'haematokrit': '#e11d48',
    'mcv': '#f97316',
    'mch': '#ea580c',
    'mchc': '#d97706',
    'thrombozyten': '#9333ea',
    'natrium': '#0284c7',
    'kalium': '#16a34a',
    'calcium': '#ca8a04',
    'cholesterin_gesamt': '#db2777',
    'hdl': '#059669',
    'ldl': '#c026d3',
    'ldl_hdl_risiko_index': '#7c3aed',
    'non_hdl_cholesterin': '#a21caf',
    'triglyzeride': '#be185d',
    'glukose': '#0d9488',
    'gesamteiweiss': '#92400e',
    'bilirubin_gesamt': '#d97706',
    'ast': '#ea580c',
    'alt': '#dc2626',
    'ggt': '#b45309',
    'alkalische_phosphatase': '#ca8a04',
    'ldh': '#6d28d9',
    'harnsaeure': '#4338ca',
    'harnstoff': '#1d4ed8',
    'kreatinin': '#0369a1',
    'egfr': '#0f766e',
    'crp': '#be123c',
    'tsh': '#4f46e5',
}


def farbe_fuer_key(key: str) -> str:
    """Erzeugt eine stabile Fallback-Farbe ohne App-Importe."""
    if key in FESTE_FARBEN:
        return FESTE_FARBEN[key]
    index = sum(ord(char) for char in key) % len(FARBEN)
    return FARBEN[index]


def setze_startfarben(apps, schema_editor):
    """Befüllt vorhandene Wissenseinträge mit stabilen Farben."""
    KnowledgeEntry = apps.get_model('knowledge', 'KnowledgeEntry')
    for entry in KnowledgeEntry.objects.select_related('analyte'):
        entry.chart_color = farbe_fuer_key(entry.analyte.key)
        entry.save(update_fields=['chart_color'])


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='chart_color',
            field=models.CharField(default='#0f5297', max_length=16),
        ),
        migrations.RunPython(setze_startfarben, migrations.RunPython.noop),
    ]
