# Generated by Django 5.2.16 on 2026-07-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('normalized_code', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LabAnalyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytes', to='labs.labgroup')),
            ],
            options={
                'ordering': ['group__sort_order', 'sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('report_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('importiert', 'Importiert'), ('review_offen', 'Review offen'), ('freigegeben', 'Freigegeben'), ('bericht_bereit', 'Bericht bereit'), ('ocr_review', 'OCR-Review')], db_index=True, default='importiert', max_length=24)),
                ('source', models.CharField(db_index=True, default='demo', max_length=40)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.patient')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sex', models.CharField(choices=[('weiblich', 'Weiblich'), ('maennlich', 'Männlich'), ('divers', 'Divers'), ('unbekannt', 'Unbekannt'), ('alle', 'Alle')], default='alle', max_length=16)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lower', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('upper', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('source_note', models.CharField(blank=True, max_length=240)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='labs.labanalyte')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_ranges', to='labs.labunit')),
            ],
        ),
        migrations.CreateModel(
            name='LabValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('hoch', 'Hoch'), ('niedrig', 'Niedrig'), ('review', 'Review')], db_index=True, default='normal', max_length=16)),
                ('priority', models.CharField(choices=[('niedrig', 'Niedrig'), ('mittel', 'Mittel'), ('hoch', 'Hoch')], db_index=True, default='niedrig', max_length=16)),
                ('review_status', models.CharField(choices=[('geprueft', 'Geprüft'), ('review', 'Review')], db_index=True, default='geprueft', max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=100)),
                ('hint', models.TextField(blank=True)),
                ('original_text', models.TextField(blank=True)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='labs.labanalyte')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='labs.labreport')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='labs.labunit')),
                ('reference_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='labs.referencerange')),
            ],
            options={
                'ordering': ['analyte__group__sort_order', 'analyte__sort_order', 'analyte__display_name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_name', models.CharField(max_length=160)),
                ('raw_value', models.CharField(max_length=80)),
                ('corrected_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('raw_unit', models.CharField(max_length=40)),
                ('original_text', models.TextField(blank=True)),
                ('original_label', models.CharField(blank=True, max_length=120)),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('korrigiert', 'Korrigiert'), ('bestaetigt', 'Bestätigt'), ('verworfen', 'Verworfen'), ('blockiert', 'Blockiert')], db_index=True, default='offen', max_length=16)),
                ('source', models.CharField(choices=[('pdf_text', 'PDF-Text'), ('ocr', 'OCR'), ('manuell', 'Manuell'), ('demo', 'Demo')], db_index=True, default='pdf_text', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('parser_hints', models.JSONField(blank=True, default=list)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_candidates', to='labs.labanalyte')),
                ('corrected_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_candidates', to='labs.labunit')),
                ('lab_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_candidates', to='labs.labvalue')),
                ('reference_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_candidates', to='labs.referencerange')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_candidates', to='labs.labreport')),
            ],
            options={
                'ordering': ['status', 'confidence', 'analyte__display_name'],
            },
        ),
        migrations.AddIndex(
            model_name='labanalyte',
            index=models.Index(fields=['group', 'is_active'], name='labs_labana_group_i_b28950_idx'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['patient', '-report_date'], name='labs_labrep_patient_207629_idx'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['status', '-report_date'], name='labs_labrep_status_02bbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='referencerange',
            index=models.Index(fields=['analyte', 'unit', 'sex'], name='labs_refere_analyte_2bf088_idx'),
        ),
        migrations.AddConstraint(
            model_name='referencerange',
            constraint=models.UniqueConstraint(fields=('analyte', 'unit', 'sex', 'age_min', 'age_max', 'lower', 'upper'), name='unique_reference_range'),
        ),
        migrations.AddIndex(
            model_name='labvalue',
            index=models.Index(fields=['report', 'status'], name='labs_labval_report__cda617_idx'),
        ),
        migrations.AddIndex(
            model_name='labvalue',
            index=models.Index(fields=['analyte', 'status'], name='labs_labval_analyte_1b3515_idx'),
        ),
        migrations.AddIndex(
            model_name='labvalue',
            index=models.Index(fields=['review_status', 'confidence'], name='labs_labval_review__43062b_idx'),
        ),
        migrations.AddConstraint(
            model_name='labvalue',
            constraint=models.UniqueConstraint(fields=('report', 'analyte'), name='unique_value_per_report_analyte'),
        ),
        migrations.AddIndex(
            model_name='reviewcandidate',
            index=models.Index(fields=['report', 'status'], name='labs_review_report__ee7941_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcandidate',
            index=models.Index(fields=['source', 'status'], name='labs_review_source_ebdfce_idx'),
        ),
    ]
