# Generated by Django 5.2.16 on 2026-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('display_name', models.CharField(db_index=True, max_length=180)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('weiblich', 'Weiblich'), ('maennlich', 'Männlich'), ('divers', 'Divers'), ('unbekannt', 'Unbekannt')], default='unbekannt', max_length=16)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lifestyle', models.CharField(blank=True, max_length=240)),
                ('context', models.CharField(blank=True, max_length=240)),
                ('source', models.CharField(choices=[('demo', 'Demo'), ('verlauf', 'Verlauf'), ('ocr', 'OCR'), ('manuell', 'Manuell')], db_index=True, default='manuell', max_length=16)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('review', 'Review'), ('import', 'Import'), ('bericht', 'Bericht'), ('leer', 'Leer')], db_index=True, default='leer', max_length=16)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['source', 'status'], name='patients_pa_source_026906_idx'), models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx')],
            },
        ),
    ]
