# Generated by Django 5.2.16 on 2026-07-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('report_date', models.DateField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('bereit', 'Bereit'), ('freigegeben', 'Freigegeben')], db_index=True, default='entwurf', max_length=20)),
                ('total_status', models.CharField(max_length=240)),
                ('total_text', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('checked_values', models.PositiveSmallIntegerField(default=0)),
                ('normal_values', models.PositiveSmallIntegerField(default=0)),
                ('abnormal_values', models.PositiveSmallIntegerField(default=0)),
                ('review_values', models.PositiveSmallIntegerField(default=0)),
                ('disclaimer', models.TextField()),
                ('lab_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='labs.labreport')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='patients.patient')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=80)),
                ('question', models.TextField()),
                ('area', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reports.patientreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('beachten', 'Beachten'), ('wichtig', 'Wichtig')], default='normal', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='reports.patientreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.patientreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=80)),
                ('area', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('source_date', models.CharField(max_length=80)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='reports.patientreport')),
            ],
            options={
                'ordering': ['area', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='patientreport',
            index=models.Index(fields=['patient', '-report_date'], name='reports_pat_patient_c11d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientreport',
            index=models.Index(fields=['status', '-report_date'], name='reports_pat_status_8d61ae_idx'),
        ),
    ]
