# Generated by Django 5.2.16 on 2026-07-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/')),
                ('filename', models.CharField(max_length=220)),
                ('test_person_label', models.CharField(blank=True, max_length=180)),
                ('analysis_type', models.CharField(choices=[('textschicht', 'Textschicht'), ('ocr', 'OCR'), ('demo', 'Demo')], db_index=True, default='textschicht', max_length=20)),
                ('status', models.CharField(choices=[('wartet', 'Wartet'), ('analysiert', 'Analysiert'), ('review', 'Review'), ('abgeschlossen', 'Abgeschlossen'), ('fehler', 'Fehler')], db_index=True, default='wartet', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('pipeline_step', models.CharField(default='Upload wartet', max_length=160)),
                ('ocr_status', models.CharField(choices=[('nicht_erforderlich', 'Nicht erforderlich'), ('erforderlich', 'Erforderlich'), ('aktiv', 'Aktiv'), ('abgeschlossen', 'Abgeschlossen'), ('fehler', 'Fehler')], db_index=True, default='nicht_erforderlich', max_length=24)),
                ('recognized_values', models.PositiveSmallIntegerField(default=0)),
                ('uncertain_values', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=140)),
                ('values_count', models.PositiveSmallIntegerField(default=0)),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('review', 'Review'), ('fehler', 'Fehler')], default='normal', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='imports.importjob')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64)),
                ('time_label', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='info', max_length=24)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='imports.importjob')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('erledigt', 'Erledigt'), ('aktiv', 'Aktiv'), ('wartet', 'Wartet'), ('fehler', 'Fehler'), ('uebersprungen', 'Übersprungen')], default='wartet', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='imports.importjob')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', '-created_at'], name='imports_imp_status_d38bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['analysis_type', 'ocr_status'], name='imports_imp_analysi_815f99_idx'),
        ),
        migrations.AddConstraint(
            model_name='importstep',
            constraint=models.UniqueConstraint(fields=('job', 'key'), name='unique_step_per_import_job'),
        ),
    ]
